### PR TITLE
Fix card overflow issue on 1/2 and 1/3 width

### PR DESCRIPTION
**Pull request by shawngoh87**

### CODE REVIEW

**Comment by shawngoh87** [comment]
@m-a-k-o 
On setting the width() of the cards to 1/2 or 1/3, Nova appends a ```card-panel``` class to the first ```<div>```, which fixes the height to 150px, causing the table to overflow.

**Comment by m-a-k-o** [comment]
Hi , thanks for PR. Can me send overflow scenario ? 

Why did you change w-full to 1/2?

**Comment by shawngoh87** [comment]
I have reverted w-1/2 back to w-full in 425a4f66, that's a mistake.

I'll attach the screenshots and snippets later.

**Comment by m-a-k-o** [comment]
Thanks. 

Maybe we can also omit css and use only h-auto instead.

**Comment by shawngoh87** [comment]
Original issue - using width('1/2')
image

After removing outer ```<div></div>```
image

**Comment by shawngoh87** [comment]
> Thanks.
> 
> Maybe we can also omit css and use only h-auto instead.

h-auto sounds cleaner, thanks for the suggestions, I'll add them in.

**Comment by m-a-k-o** [comment]
Perfect :) Thanks .  I will merge and publish new version after ;)

**Comment by m-a-k-o** [comment]
@shawngoh87 Released as 3.0.1

**Comment by m-a-k-o** [comment]
Thank you for your contribution :)

**Comment by shawngoh87** [comment]
Great! Thanks for your swift response 💯

**Pull request merged**
